# .github/workflows/unittest.yml

name: Django Unit Tests

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  test:
    name: Run Django Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust according to your project setup

    - name: Run tests
      run: |
        python manage.py test  # Adjust manage.py path if necessary

  docker:
    runs-on: ubuntu-latest
    needs: test 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run with Docker Compose
      run: |
        docker-compose up -d --build
